2025-03-05 19:06:01,825 - prediction_model - INFO - Logging to file: C:\Users\clubs\Desktop\Prediction Model\data\Logs\prediction_model_20250305_190601.log
2025-03-05 19:06:03,593 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:06:03,651 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:06:08,077 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:06:08,449 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:06:44,197 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:06:44,258 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:07:59,666 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:07:59,715 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:09:35,977 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:09:36,052 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:09:47,842 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:09:47,906 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:17:30,279 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:17:30,390 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:25:06,423 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:25:06,510 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:25:14,030 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:25:14,090 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:33:23,829 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:33:23,907 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:33:27,583 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:33:27,654 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:33:38,205 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:33:38,283 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 19:34:21,657 - prediction_model - ERROR - Error in update_progress_display: 'metrics_container'
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_error.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_data.py", line 187, in update_progress_display
    with st.session_state["metrics_container"].container():
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\session_state_proxy.py", line 93, in __getitem__
    return get_session_state()[key]
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\streamlit\runtime\state\safe_session_state.py", line 109, in __getitem__
    raise KeyError(key)
KeyError: 'metrics_container'
2025-03-05 19:34:24,694 - prediction_model - ERROR - Error in create_interactive_price_chart: ['date']
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 75, in create_interactive_price_chart
    df = df.dropna(subset=["date"])
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6561, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: ['date']
2025-03-05 19:34:24,747 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
