2025-03-05 23:36:03,931 - prediction_model - INFO - Logging to file: C:\Users\clubs\Desktop\Prediction Model\data\Logs\prediction_model_20250305_233603.log
2025-03-05 23:36:09,391 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:36:10,932 - prediction_model - ERROR - Error showing advanced dashboard tabs: DataFrame.sort_values() missing 1 required positional argument: 'by'
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'
2025-03-05 23:38:33,760 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:38:33,869 - prediction_model - ERROR - Error showing advanced dashboard tabs: DataFrame.sort_values() missing 1 required positional argument: 'by'
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'
2025-03-05 23:39:34,488 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:39:34,638 - prediction_model - ERROR - Error showing advanced dashboard tabs: DataFrame.sort_values() missing 1 required positional argument: 'by'
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'
2025-03-05 23:46:31,980 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:46:32,129 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-05 23:48:32,733 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:48:32,864 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-05 23:48:37,976 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:48:38,118 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-05 23:50:38,507 - prediction_model - ERROR - Error calculating indicators: Cannot set a DataFrame with multiple columns to the single column Volume_Ratio
2025-03-05 23:50:38,689 - prediction_model - ERROR - Error showing advanced dashboard tabs: None
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_visualization.py", line 533, in show_advanced_dashboard_tabs
    close_corr = corr_matrix['Close'].drop('Close').sort_values(by=None, ascending=False)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\frame.py", line 6912, in sort_values
    k = self._get_label_or_level_values(by, axis=axis)
  File "C:\Users\clubs\anaconda3\envs\ml_env\lib\site-packages\pandas\core\generic.py", line 1850, in _get_label_or_level_values
    raise KeyError(key)
KeyError: None
2025-03-05 23:51:51,486 - prediction_model - ERROR - Critical error in main dashboard: name 'load_latest_progress' is not defined
Traceback (most recent call last):
  File "C:\Users\clubs\Desktop\Prediction Model\src\dashboard\dashboard\dashboard_core.py", line 315, in main_dashboard
    progress = load_latest_progress(ticker=ticker, timeframe=timeframe)
NameError: name 'load_latest_progress' is not defined
